//
//  MoviesListWorker.swift
//  MoviesCleanSwift
//
//  Created by Anton Gutkin on 18.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MoviesListNetworkingWorkerLogic {
    var service: MoviesNetworkingServiceProtocol { get }
    
    init(with service: MoviesNetworkingServiceProtocol)
    
    func getMovies(title: String, page: Int, completion: @escaping (Result<MovieAPIResponse?, Error>) -> Void)
}

class MoviesListWorker: MoviesListNetworkingWorkerLogic {
    internal let service: MoviesNetworkingServiceProtocol
    
    required init(with service: MoviesNetworkingServiceProtocol = MoviesNetworkingService()) {
        self.service = service
    }
    
    func getMovies(title: String, page: Int = 1, completion: @escaping (Result<MovieAPIResponse?, Error>) -> Void) {
        service.getMovies(with: title, page: page, completion: completion)
    }
}
