//
//  MovieDetailsPresenter.swift
//  MoviesCleanSwift
//
//  Created by Anton Gutkin on 20.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailsPresentationLogic {
    var viewController: MovieDetailsDisplayLogic? { get set }
    
    func presentMovieDetails(response: MovieDetails.Response)
}

class MovieDetailsPresenter {
    weak var viewController: MovieDetailsDisplayLogic?
}

extension MovieDetailsPresenter: MovieDetailsPresentationLogic {
    func presentMovieDetails(response: MovieDetails.Response) {
        let movieDetailsConfiguration = MovieDetailsViewControllerConfiguration(with: response.movie)
        viewController?.displayMovieDetails(viewModel: MovieDetails.UI.ViewModel(configuration: movieDetailsConfiguration))
    }
}

