//
//  MoviesListModels.swift
//  MoviesCleanSwift
//
//  Created by Anton Gutkin on 18.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MoviesList {
    enum UI {
        typealias CellConfiguration = (cellType: MoviesList.UI.CellType, configuration: BaseTableviewCellConfiguration)
        
        enum CellType {
            case loading
            case movie
        }
        
        struct ViewModel {
            let cellConfigurations: [CellConfiguration]
        }
        
        struct Message {
            let title: String
            let description: String
        }
    }
    
    enum Movies {
        struct Request {
            let title: String
        }

        struct Response {
            let movieAPIResponse: MovieAPIResponse
        }
    }
}
