//
//  MoviesListRouter.swift
//  MoviesCleanSwift
//
//  Created by Anton Gutkin on 18.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MoviesListRoutingLogic {
    func routToMovieDetails()
}

protocol MoviesListDataPassing {
    var dataStore: MoviesListDataStore? { get }
}

class MoviesListRouter: NSObject, MoviesListRoutingLogic, MoviesListDataPassing {
    weak var viewController: MoviesListViewController?
    var dataStore: MoviesListDataStore?
    
    func routToMovieDetails() {
        let destinationViewController = MovieDetailsViewController.loadFromNib()
        
        guard let source = dataStore, var destinationDataStore = destinationViewController.router?.dataStore else {
            return
        }
        
        passDataToProductDetails(source: source, destination: &destinationDataStore)
        navigateToMovieDetails(source: viewController, destination: destinationViewController)
    }

    func navigateToMovieDetails(source: MoviesListViewController?, destination: MovieDetailsViewController) {
        source?.navigationController?.present(destination, animated: true)
    }
    
    func passDataToProductDetails(source: MoviesListDataStore, destination: inout MovieDetailsDataStore) {
        guard let selectedRow = viewController?.selectedRow(), selectedRow < source.movies.count else {
            return
        }
        
        let selectedMovieResponse = MovieDetails.Response(movie: source.movies[selectedRow])
        destination.movie = selectedMovieResponse
    }
}
