//
//  MovieDetailsWorker.swift
//  MoviesCleanSwift
//
//  Created by Anton Gutkin on 20.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailsNetworkingWorkerLogic {
    var service: MoviesNetworkingServiceProtocol { get }
    
    init(with service: MoviesNetworkingServiceProtocol)
}

class MovieDetailsWorker: MovieDetailsNetworkingWorkerLogic {
    internal let service: MoviesNetworkingServiceProtocol
    
    required init(with service: MoviesNetworkingServiceProtocol = MoviesNetworkingService()) {
        self.service = service
    }
}
